name: "halfstring"
permalink: /:year/:month/:day/:title.html

author: "wayne"
atom-baseurl: "http://halfstring.github.io"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://halfstring.github.io
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

